name: Build SOPMEX Remote

on:
  workflow_dispatch:

jobs:
  build-sopmex:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "sopmex"
